sudo: false

language: node_js

node_js:
  - "4.4.7"

env:
  - ATOM_CHANNEL=beta CXX=g++-4.8

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - npm install -g npm

script:
  - ./script/cibuild

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - g++-4.8
