sudo: false

language: node_js

node_js:
  - "6.1"

env:
  - ATOM_CHANNEL=beta

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - ./script/cibuild

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
